import {StyleSheet, Platform} from 'react-native';

const dynamicStyles = (appStyles, colorScheme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },
    cardBox: {
      paddingBottom: 30,
    },
    cardStyle: {
      backgroundColor: appStyles.colorSet[colorScheme].grey0,
      textColor: appStyles.colorSet[colorScheme].blackColor,
      placeholderColor: appStyles.colorSet[colorScheme].grey9,
      borderRadius: 8,
    },
    cardInputStyle: {
      width: '100%',
      height: Platform.OS === 'ios' ? 150 : 140,
      borderColor: appStyles.colorSet[colorScheme].grey9,
      borderRadius: 8,
    },
    divider: {
      borderBottomColor: '#ddd',
      borderBottomWidth: 1,
    },
    flexContainer: {
      flexDirection: 'row',
    },
    headerTitle: {
      fontSize: 20,
      fontFamily: 'PlusJakartaSans-Regular',
      fontWeight: '400',
      textAlign: 'center',
      paddingVertical: 10,
      color: appStyles.colorSet[colorScheme].blackColor,
    },
    title: {
      fontSize: 17,
      fontFamily: 'PlusJakartaSans-Regular',
      fontWeight: '700',
      // paddingBottom: 5,
      color: appStyles.colorSet[colorScheme].blackColor,
    },
    text: {
      fontSize: 16,
      fontFamily: 'PlusJakartaSans-Regular',
      fontWeight: '400',
      color: appStyles.colorSet[colorScheme].blackColor,
      paddingVertical: 5,
    },
    boxContainer: {
      borderRadius: 10,
      paddingBottom: 20,
      padding: 15,
      marginTop: 20,
      backgroundColor: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
      shadowColor: '#006',
      borderColor: '#ddd',
      borderWidth: 0.5,
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.05,
      shadowRadius: 0.5,
      elevation: 5,
    },
    boxHeader: {
      paddingBottom: 10,
    },
    boxBottomHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingBottom: 10,
    },
    boxBody: {
      paddingTop: 10,
    },
    halfWidth: {
      width: '50%',
    },
    makerImg: {
      width: 30,
      height: 30,
      resizeMode: 'contain',
    },
    valoraImg: {
      width: 30,
      height: 30,
      marginRight: 10,
    },
    cardIcon: {
      position: 'absolute',
      left: 10,
      color: appStyles.colorSet[colorScheme].blackColor,
    },
    listContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 10,
      backgroundColor: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
      justifyContent: 'space-between',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.25,
      shadowRadius: 0.5,
      elevation: 5,
    },
    btnPayContainer: {
      alignItems: 'center',
      alignSelf: 'flex-end',
      backgroundColor: appStyles.colorSet[colorScheme].mainThemeForegroundColor,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'white',
      width: '50%',
      marginHorizontal: 1,
    },
    btnNewCardContainer: {
      alignItems: 'center',
      alignSelf: 'flex-end',
      // backgroundColor: appStyles.colorSet[colorScheme].mainThemeForegroundColor,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: appStyles.colorSet[colorScheme].mainThemeForegroundColor,
      width: '50%',
      marginHorizontal: 1,
    },
    btnContainer: {
      alignItems: 'center',
      alignSelf: 'flex-end',
      backgroundColor: appStyles.colorSet[colorScheme].mainColor,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'white',
      width: '30%',
    },
    btnDisableContainer: {
      alignItems: 'center',
      alignSelf: 'flex-end',
      backgroundColor: appStyles.colorSet[colorScheme].grey6,
      padding: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'white',
      width: '30%',
    },
    btnText: {
      fontSize: 15,
      fontWeight: '500',
      lineHeight: 20,
      fontFamily: 'PlusJakartaSans-Regular',
      color: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },
    btnCardText: {
      fontSize: 16,
      fontFamily: 'PlusJakartaSans-Regular',
      fontWeight: '500',
      color: appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },

    // Modal
    modalView: {
      paddingHorizontal: 10,
      margin: 0,
    },
    modalHeader: {
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      paddingBottom: 23,
    },
    Modalcontent: {
      backgroundColor: 'white',
      padding: 22,
      justifyContent: 'center',
      // alignItems: 'center',
      borderRadius: 20,
      borderColor: 'rgba(0, 0, 0, 0.1)',
      width: '100%',
    },
    modalContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardInputBox: {
      width: '95%',
      height: 45,
      borderWidth: 1,
      borderColor: appStyles.colorSet[colorScheme].grey3,
      paddingHorizontal: 10,
      color: appStyles.colorSet[colorScheme].blackColor,
      borderRadius: 8,
      margin: 0,
    },
    inputContainerStyle: {
      marginLeft: 0,
    },
    btnBoxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 5,
      marginTop: 10,
    },
    image: {
      width: 50,
      height: 50,
      marginBottom: 20,
    },
    inputContainer: {
      justifyContent: 'center',
      marginTop: 10,
    },
    inputBox: {
      width: '100%',
      paddingLeft: 50,
      height: 45,
      borderWidth: 1,
      borderColor: appStyles.colorSet[colorScheme].grey3,
      paddingHorizontal: 10,
      color: appStyles.colorSet[colorScheme].blackColor,
      borderRadius: 8,
    },
    leftContainer: {
      borderTopEndRadius: 0,
      borderBottomEndRadius: 0,
    },
    rightContainer: {
      borderLeftWidth: 0,
      borderTopStartRadius: 0,
      borderBottomStartRadius: 0,
    },
    codeFieldContainer: {
      marginTop: 10,
      marginBottom: 20,
      alignItems: 'center',
    },
    codeInputCell: {
      width: 50,
      height: 50,
      lineHeight: 30,
      fontSize: 26,
      fontFamily: 'PlusJakartaSans-Regular',
      fontWeight: '400',
      textAlign: 'center',
      marginLeft: 8,
      color: appStyles.colorSet[colorScheme].blackColor,
      borderBottomColor: appStyles.colorSet[colorScheme].grey3,
      // borderBottomWidth: 6,
      backgroundColor: appStyles.colorSet[colorScheme].grey3,
      // IOS
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.22,
      //Android
      elevation: 3,
      borderRadius: 10,
      alignItems: 'center',
      textAlignVertical: 'bottom',
    },
    focusCell: {
      borderColor: '#000',
      backgroundColor: appStyles.colorSet[colorScheme].grey3,
    },
    orTextStyle: {
      marginTop: 40,
      marginBottom: 10,
      alignSelf: 'center',
      color: appStyles.colorSet[colorScheme].mainTextColor,
    },
    activeCell: {
      paddingTop: Platform.OS === 'ios' ? 10 : 0,
      // backgroundColor : appStyles.colorSet[colorScheme].mainThemeBackgroundColor,
    },
    centerContainer: {
      alignItems: 'center',
      justifyContent: 'space-between',
      flexDirection: 'row',
    },
    reasonContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 5,
    },
    checkBox: {
      width: 20,
      height: 20,
      marginRight: 20,
    },
  });
};

export default dynamicStyles;
